### ISSUE TITLE
No password hashes loaded

### ISSUE THREAD

**Issue by edisonchen2019** [openwall/john-packages#12] opened 2021-06-14 13:26 UTC
unshadow passwd shadow > full
john full --wordlist=/usr/share/wordlists/rockyou.txt

It just throw the error "No password hashes loaded"

**Comment by claudioandre-br** [comment] 2021-06-14 13:41
There are some reasons for the message. From the FAQ file inside doc folder:

> A: All of the password hashes found in the file [...] might be already cracked by previous
invocations of John. 

Could you try to make your point clearer? BTW: to unshadow you need root privileges, not clear if you are running all stuff properly. Have you listed the content of the `full` file? Is it empty?

BTW: 
- if you need support as an end-user, ask for help on the mailing list john-users at lists.openwall.com (but first see the archives at http://www.openwall.com/lists/john-users/ and make sure you set a descriptive message Subject when you post).

**Comment by edisonchen2019** [comment] 2021-06-14 13:48
i am in a root privileges and 'full' file contain the hashes.

**Comment by claudioandre-br** [comment] 2021-06-14 13:52
Just in case you are using a brand new distro, so:
> A: Your password hash or cipher type(s) might not be supported by John,
or at least by the version and build of John that you're using.  If
you're using a non-jumbo version, you will likely want to try -jumbo
instead, which supports a lot of additional hash and cipher types.

In this case, I will report the issue upstream. Anyway, please, create a fake user (at least, change some password), so you can safely share the hash with us. And: share details about you environment and about john, including `john --list=build-info`.

**Comment by edisonchen2019** [comment] 2021-06-14 14:20
hey, it did help for the flag --format=crypt 
john -wordlist=/usr/share/wordlists/rockyou.txt mypasswd --format=crypt 

Below is my env info:
No LSB modules are available.
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2021.2
Codename:       kali-rolling

John: 1.9.0-Jumbo-1-0kali3

**Comment by claudioandre-br** [comment] 2021-06-14 14:33
The issue is `off-topic` here (in the `*-packages` repo). The package was created by kali team itself (or by a 3rd packager).

Please consider moving it to `https://github.com/openwall/john` as a request to support whatever kali is using as its hashing algorithm.

**Closed by claudioandre-br** 2021-06-14 14:33 UTC
Labels: invalid

**Comment by solardiz** [comment] 2021-06-14 14:37
> Please consider moving it to `https://github.com/openwall/john`

There is no need - we already have proper issues opened in there.
